### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by a4aditya** [accordproject/cicero-template-library#324]
The link for Cicero Documentation on all of the Template Documentations is broken.
Link to the Page: https://templates.accordproject.org/acceptance-of-delivery@0.13.1.html (url)
![1](https://user-images.githubusercontent.com/39999719/75721148-d8ae3c00-5cfd-11ea-8bc6-f51a68e8f62a.png)

![2](https://user-images.githubusercontent.com/39999719/75721510-7c97e780-5cfe-11ea-9ad5-5f41d1ecb9cc.png)

Previous link : [https://docs.accordproject.org/docs/cicero.html](url)
The new link should be: [https://docs.accordproject.org/docs/started-installation.html](url)

what is your suggestion @irmerk  @jeromesimeon what should be the new link for the Cicero Documenation Reference?

**Comment by irmerk** [comment]
Good catch. I believe https://docs.accordproject.org/docs/started-hello would be the best link maybe.

**Comment by a4aditya** [comment]
thanks for the input I'll change the link now and will send a pull request

**Comment by jeromesimeon** [comment]
> Good catch. I believe https://docs.accordproject.org/docs/started-hello would be the best link maybe.

Good catch indeed. I don't think that link corresponds to the text though?

**Comment by jeromesimeon** [comment]
Either update the text or use this link I think: https://docs.accordproject.org/docs/tutorial-nodejs.html

(I would prefer the former)

**Comment by jeromesimeon** [comment]
This should be fixed in the templates: https://github.com/accordproject/cicero-template-library/tree/master/views

**Comment by a4aditya** [comment]
I have changed the link and pushing the changes please review.

**Comment by Aniruddha-Shriwant** [comment]
@jeromesimeon I'm willing to work on this

**Comment by dinuka-rp** [comment]
@jeromesimeon I was just pointing out this issue [in the tech docs](https://github.com/accordproject/techdocs/issues/349). Didn't know that it was generated from the developers.njk file within this repository till @mttrbrts pointed it out.

Will be willing to get assigned and submit a PR on this issue as [recommended by Matt](https://github.com/accordproject/techdocs/issues/349#issuecomment-797777655) or by updating the template file and rebuilding.

Since @Aniruddha-Shriwant was here before me, I guess he can take a shot at the fix first :)

**Comment by Aniruddha-Shriwant** [comment]
> This should be fixed in the templates: https://github.com/accordproject/cicero-template-library/tree/master/views

@jeromesimeon I had changed `.\views\developers.njk` and then run `npm run build` but when I open any of the HTML files from `build\` I found that the issue was not fixed...
